# Site settings
title: Constraint Lab
email: boston@constraintlab.com
description: System exploration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://constraintlab.com" # the base hostname & protocol for your site
x_username: bostonou
linkedin_username: jonboston

# Build settings
markdown: kramdown
future: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /blog/:title.html

sass:
  style: compressed
  sass_dir: _sass

