name: Build every four hours

on:
  schedule:
   - cron: '0 */4 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: "Curl - Kick off Pages Build"
      shell: bash
      run: |
        curl -X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/Constraint-Lab/Constraint-Lab.github.io/pages/builds
